name: action_on_label

permissions:
  actions: write        
  contents: write       
  issues: write         
  pull-requests: write  
  packages: write
  
on:
  issues:
    types:
      - labeled
  pull_request_target:
    types:
      - labeled

jobs:
  merge_and_close_issue_or_PR_on_level_assignment:
    if: github.event.action == 'labeled' && startsWith(github.event.label.name, 'level')
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.pull_request.html_url }} --body "@${{ github.event.pull_request.user.login }}
            
            🎉 Great news! Your pull request has been successfully merged. We appreciate your contribution!
            
            🙌 Please feel free to check out the other issues on our website and see if there’s anything else you’d like to contribute with. 💻"
            gh pr merge ${{ github.event.pull_request.number }} --merge --repo ${{ github.repository }} --subject "Merge Merge pull request #${{ github.event.pull_request.number }} from ${{ github.event.pull_request.head.ref }}"
